name: KrakenMobcoins
version: 2.1
api-version: 1.13
authors: [aglerr, ItzStormz]
main: me.aglerr.krakenmobcoins.MobCoins
softdepend: [PlaceholderAPI, SuperMobCoins, MythicMobs, WildStacker]

commands:
  mobcoins:
    aliases: [mc]