name: KrakenMobcoins
version: 1.9
api-version: 1.13
author: aglerr
main: me.aglerr.krakenmobcoins.MobCoins
softdepend: [PlaceholderAPI, SuperMobCoins, MythicMobs]

commands:
  mobcoins:
    aliases: [mc]