name: KrakenMobcoins
version: 2.0
api-version: 1.13
author: aglerr
main: me.aglerr.krakenmobcoins.MobCoins
softdepend: [PlaceholderAPI, SuperMobCoins, MythicMobs, WildStacker]

commands:
  mobcoins:
    aliases: [mc]